TEST DATA
define table chain;

delete from chain;
select * from chain;

create chain:data1_step01 content {
    "data":"data1_step01",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data1_step02 content {
    "data":"data1_step02",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data1_step03 content {
    "data":"data1_step03",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data1_step04 content {
    "data":"data1_step04",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data1_step05 content {
    "data":"data1_step05",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data1_step06 content {
    "data":"data1_step06",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data1_step07 content {
    "data":"data1_step07",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data1_step08 content {
    "data":"data1_step08",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data1_step09 content {
    "data":"data1_step09",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data1_step10 content {
    "data":"data1_step10",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data1_step11 content {
    "data":"data1_step11",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};

create chain:data2_step01 content {
    "data":"data2_step01",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data2_step02 content {
    "data":"data2_step02",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data2_step03 content {
    "data":"data2_step03",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data2_step04 content {
    "data":"data2_step04",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data2_step05 content {
    "data":"data2_step05",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data2_step06 content {
    "data":"data2_step06",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data2_step07 content {
    "data":"data2_step07",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data2_step08 content {
    "data":"data2_step08",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data2_step09 content {
    "data":"data2_step09",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data2_step10 content {
    "data":"data2_step10",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data2_step11 content {
    "data":"data2_step11",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};

create chain:data3_step01 content {
    "data":"data3_step01",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data3_step02 content {
    "data":"data3_step02",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data3_step03 content {
    "data":"data3_step03",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data3_step04 content {
    "data":"data3_step04",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data3_step05 content {
    "data":"data3_step05",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data3_step06 content {
    "data":"data3_step06",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data3_step07 content {
    "data":"data3_step07",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data3_step08 content {
    "data":"data3_step08",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data3_step09 content {
    "data":"data3_step09",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data3_step10 content {
    "data":"data3_step10",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data3_step11 content {
    "data":"data3_step11",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};

create chain:data4_step01 content {
    "data":"data4_step01",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data4_step02 content {
    "data":"data4_step02",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data4_step03 content {
    "data":"data4_step03",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data4_step04 content {
    "data":"data4_step04",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data4_step05 content {
    "data":"data4_step05",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data4_step06 content {
    "data":"data4_step06",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data4_step07 content {
    "data":"data4_step07",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data4_step08 content {
    "data":"data4_step08",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data4_step09 content {
    "data":"data4_step09",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data4_step10 content {
    "data":"data4_step10",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data4_step11 content {
    "data":"data4_step11",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};

create chain:data5_step01 content {
    "data":"data5_step01",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data5_step02 content {
    "data":"data5_step02",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data5_step03 content {
    "data":"data5_step03",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data5_step04 content {
    "data":"data5_step04",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data5_step05 content {
    "data":"data5_step05",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data5_step06 content {
    "data":"data5_step06",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data5_step07 content {
    "data":"data5_step07",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data5_step08 content {
    "data":"data5_step08",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data5_step09 content {
    "data":"data5_step09",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data5_step10 content {
    "data":"data5_step10",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
create chain:data5_step11 content {
    "data":"data5_step11",
    "waktu":{
        "disimpan":time::now(),
        "timezone":time::timezone()
    }
};
